services:
  n8n-workspace:
    container_name: n8n-workspace
    build: .
    environment:
      - USERNAME=abcd
    working_dir: /workspace
    volumes:
      - n8n-workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock #optional

volumes:
  n8n-workspace:
